sudo: required

services:
  - docker
  - mongodb

language: node_js

node_js:
  - '8.4'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gulp-cli
  - npm install -g gulp-cli
  - npm install --quiet

script: gulp test

after_success:
  - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
  - export REPO=armandorvila/todo-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -q -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO